name: Test only

on:
  push:
    branches:
      - test
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup DB
      env:
        REDIS_URL: redis://localhost:6379/0
        PGHOST: localhost
        PGUSER: hakase_dev
        PGPASSWORD: hakasepass
        # PGUSER: postgres
        # PGPASSWORD: postgres
        RAILS_ENV: test
      run: |
        bundle exec rails db:setup RAILS_ENV=test
        bundle exec rake db:migrate RAILS_ENV=test

    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
      run: |
        bundler exec rspec
